CLI usage instructions in readme
simonepri/project-version pull request #9
Opened 2018-08-13 20:15 UTC by bjesuiter

I think, that the usage for the cli option should be included in the readme of the repo. 
If you want to change some things about my readme suggestion, make a comment and i'll fix it 👍

2018-08-13 21:38 UTC, simonepri requested changes

2018-08-13 21:38 UTC, simonepri commented on README.md
> +## JS Usage
Just leave that Usage

2018-08-13 21:38 UTC, simonepri commented on README.md
> +## CLI Usage
Call that CLI
Have a look to this example:
https://github.com/simonepri/osm-geojson#cli

2018-11-12 23:49 UTC, bjesuiter commented
@simonepri I thought you merged the changes after you made the changes to the branch in my repository. 
Now I discovered, that this is still pending and I got on to change the things from your request. 
Can you please check whether it's okay now?

2018-11-25 12:40 UTC, merged